version: "3"
services:
    web:
        build: ./web
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./web/etc/apache2/sites-enabled:/etc/apache2/sites-enabled
            - ./web/etc/apache2/certs:/etc/apache2/certs
            - ./web/usr/local/etc/php/conf.d/10-custom.ini:/usr/local/etc/php/conf.d/10-custom.ini
            - ./web/var/www:/var/www/
        links:
            - mysql:db

    mysql:
        image: mysql:5.5
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./mysql/var/lib/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        links:
            - mysql:db
